swagger: '2.0'
info:
  title: TomoMaster APIs
  description: Happy to code TomoMaster APIs
  version: '1.0.0'
schemes:
  - http
basePath:
produces:
  - application/json
paths:
  /api/config:
    get:
      summary: Get TomoMaster Application Configuration
      description: |
        Get TomoMaster Application Configuration
      responses:
        200:
          description: Returns a access token
        401:
          description: Unauthorized
        400:
          description: Bad Request
        406:
          description: Not Acceptable
        500:
          description: Server Internal error
      tags:
        - Config


