name: Trigger Codebuild to build and deploy tomo master

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: "ap-southeast-1"
      aws_account_id:
        required: true
        type: string
      aws_role_assume_name:
        required: true
        type: string
      codebuild_project_name:
        required: true
        type: string
      culiops_branch:
        type: string
        default: "main"
      ecs_cluster_name:
        type: string
        default: "ecs-shared-stg"
      ecs_service_name:
        type: string
        default: "api"

jobs:
  codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role_assume_name }}
      - name: Trigger CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ inputs.codebuild_project_name }}
          disable-source-override: true
          env-vars-for-codebuild: |
            AWS_DEFAULT_REGION,
            AWS_ACCOUNT_ID,
            CULIOPS_BRANCH,
            ECS_CLUSTER_NAME,
            BUILD_TYPE,
            IMAGE,
            IMAGE_TAG,
            TRIGGERED_BY,
            REPO_NAME
        env:
          AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
          AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
          CULIOPS_BRANCH: ${{ inputs.culiops_branch }}
          ECS_CLUSTER_NAME: ${{ inputs.ecs_cluster_name }}
          BUILD_TYPE: ${{ inputs.ecs_service_name }}
          IMAGE: ""
          IMAGE_TAG: ""
          TRIGGERED_BY: ${{ github.actor }}
          REPO_NAME: ${{ github.event.repository.name }}
