name: Vicsan TestNet Master

on:
  push:
    branches:
      - testnet-master

env:
  APPLICATION: "tomochain"
  ENVIRONMENT: "testnet"
  AWS_REGION: "ap-southeast-1"
  CULIOPS_BRANCH: "main"

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  set_vars:
    runs-on: ubuntu-latest
    outputs:
      aws_region: ${{ env.AWS_REGION }}
      aws_role_assume_name: "${{ env.APPLICATION }}-ci-${{ env.ENVIRONMENT }}"
      codebuild_project_name: "${{ env.APPLICATION }}-${{ env.ENVIRONMENT }}"
      culiops_branch: ${{ env.CULIOPS_BRANCH }}
      ecs_cluster_name: "${{ env.APPLICATION }}-${{ env.ENVIRONMENT }}"
    steps:
      - run: echo "Exposing ENV vars"

  deploy:
    needs: [set_vars]
    strategy:
      matrix:
        service: 
          - master-web
          - master-crawl
    uses: BuildOnViction/tomomaster/.github/workflows/deploy-by-codebuild.yml@testnet-master
    with:
      aws_region: ${{ needs.set_vars.outputs.aws_region }}
      aws_account_id: ${{ needs.set_vars.outputs.aws_account_id }}
      aws_role_assume_name: ${{ needs.set_vars.outputs.aws_role_assume_name }}
      codebuild_project_name: ${{ needs.set_vars.outputs.codebuild_project_name }}
      culiops_branch: ${{ needs.set_vars.outputs.culiops_branch }}
      ecs_cluster_name: ${{ needs.set_vars.outputs.ecs_cluster_name }}
      ecs_service_name: ${{ matrix.service }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
